### ISSUE TITLE
how to use your project

### ISSUE THREAD

**Issue by gurpartap007** [antonypro/AudioStreaming#1]
I want to stream audio from some mp3 file over localhost and listen on localhost.How I can use this program to build that.

Also what should I give in server address in client application and what port number should be in server window.I want to record voice of my laptop mike in linux.So which hardware device should I select:
command : arecord -l  showing
card 1: PCH [HDA Intel PCH], device 0: ALC3234 Analog [ALC3234 Analog]
  Subdevices: 0/1
  Subdevice #0: subdevice #0

**Comment by antonypro** [comment]
To stream an mp3 file you need to decode it in real time and them overwrite the input audio of the server by the uncompressed audio data from your mp3 file, this program doesn't supports natively this feature, but it's absolutely possible do it!

About your microphone, I made some bug fixes and the default configuration should be ok, if not you'll be warned about the error!

Hope that helps
