### ISSUE TITLE
Virtual Memory , Thread Creation Error

### ISSUE THREAD

**Issue by MS-C0d3r** [antonypro/AudioStreaming#11]
i'm using this library in RPI3.

VM size increases every time you press the 'Connect button' in the DemoClient Program.

and

VM size increase every time you press the 'Start Server' in the DemoServer Program.

Before / button press
![image](https://user-images.githubusercontent.com/46777374/59172742-b7f8f180-8b84-11e9-9976-7258b30ed7aa.png)

After / button press
![image](https://user-images.githubusercontent.com/46777374/59172769-dbbc3780-8b84-11e9-898c-85ba57f4a26b.png)

VM-Size increases even if it is not connected to the server.

Even if you're connected to a server, In my program, you have to change your input device frequently.

VM-Size continues to grow and programs shut down when you repeat Connect/Disconnect.

Or

![image](https://user-images.githubusercontent.com/46777374/59172926-87658780-8b85-11e9-8e5b-2f83f283de50.png)

![image](https://user-images.githubusercontent.com/46777374/59173128-6cdfde00-8b86-11e9-8f05-c28a86e60283.png)

The above error occurred and the server could not be accessed.

How to fix it?

Or

Is there a way to change the input device without shutting down the server?
(Keep access to the client.)

**Comment by antonypro** [comment]
I'm able to reproduce the memory leak on any platform, there is a issue with the `QThread` exit.

I'll solve the problem soon as possible.

Thank you for reporting!

**Comment by antonypro** [comment]
I released a new version that corrects the `QThread` memory leak. Please see it and tell me if the problem persists on RPI3.

Thank you!

**Comment by MS-C0d3r** [comment]
Thx antony.

I'll check it out now and leave some feedback.

**Comment by MS-C0d3r** [comment]
Thread is removed successfully and the memory is returned successfully.

Thx antony.

**Comment by antonypro** [comment]
I forgot to mention, but i added the possibility to change the input/output devices without restart the library, you can test this feature on the Broadcast Client/Server and Walkie Talkie demos.

**Comment by MS-C0d3r** [comment]
@antonypro    : )
I also checked that part.
Thank you for correcting me to that point.
