### ISSUE TITLE
source sound on client?

### ISSUE THREAD

**Issue by Vitaliycom** [antonypro/AudioStreaming#12]
Hello.
You made a great library. But I have one problem...
In order for the server to be on a static IP server, could clients be connected and broadcast among themselves, including on the server? Were the IP address and IP address server between clients?
Now I Use WalkieTalkie mode, but it's mode can't create more then one connection between two users, don't possible connect more client...

**Comment by antonypro** [comment]
@Vitaliycom: Hello, this feature is not currently supported, the WebServer do not work in Broadcast mode, so the only option actually is capture sound and transmit from the same device, on Broadcast Server mode.

This feature may be added in the future, but even if I do that, it will take time.

Thanks for the interest in the library, and sorry if its not fully achieve your goals!

**Comment by Vitaliycom** [comment]
@antonypro, Thank you for your replay! At the moment I did something like you wrote. This works, but a delay is added to the final listener. But this is not critical.
