### ISSUE TITLE
Use this project with QUdpSocket

### ISSUE THREAD

**Issue by vaishyavivek** [antonypro/AudioStreaming#13]
This is really a nice project, although I couldn't find an example specific to my problem (may be its there). 
I wish to stream my audio over UDP using QUdpSocket. The connection is established and thus I just want to pass the Voice Over Udp. How can I implement this using your project. It would be much better if this can do 2 way communication (Record from Mic and play incoming voice). Thanks

**Comment by antonypro** [comment]
Hi! I'm working on a new version where UDP will be supported, and others improvements. Currently, UDP is not supported and maybe too hard to change using the current source code.

However, it may take some time!

Thank you for your feedback!
