### ISSUE TITLE
how to implement a two way client to talk and listen ?

### ISSUE THREAD

**Issue by amrkamal2025** [antonypro/AudioStreaming#3]
this project is the best on git hub for Qt VOIP i have never seen and it works fine but i try to implement the two ways on your code i mean that the client can talk and listen and server is just to regulate the data and transfer it but i can't and it doesn't work 
when i try to to make my own the voice chat using QTcpSocket as you and the qt voice format as you too but it is not clear there is a sound distribution  i ask my question  [here](http://stackoverflow.com/questions/38818872/voice-not-clear-in-voice-chat-using-qt-android) 
please if you can help me in this or see my question and guide me what to do so the sound works fine as your project
i attach  to you what i have reach in my project that client can talk and listen and server to transfer data 
and thank  you
[VoiceServer.zip](https://github.com/antonypro/AudioStreaming/files/433348/VoiceServer.zip)
[VoiceClient.zip](https://github.com/antonypro/AudioStreaming/files/433349/VoiceClient.zip)

**Comment by antonypro** [comment]
Hi @amrkamal2025, I'm working to convert this example into a static library, to keep the source code of you and others users of this project clean and easy to update, while allows me to develop a better but complex library! More integration with Opus audio codec on Android devices and more! I only need to some time to implement these features! 

Please wait, thank you!

**Comment by amrkamal2025** [comment]
sorry again but i need it very soon i try this please take a look at them 
they work 100 % on windows we can say computer in general
but when i use it on android the sound comes very late not real time 
i face this problem on windows when i try i solve it by change time to buffer to 100 and it solve
i try to decrease time to buffer for android and it doesn't work too
please any help i will appreciate that, give me any hint of why that my code is very close to your code i use your input file 
and the same code of output why it's late ?
[VoiceChatServer.zip](https://github.com/antonypro/AudioStreaming/files/440163/VoiceChatServer.zip)
[VoiceChatClient.zip](https://github.com/antonypro/AudioStreaming/files/440162/VoiceChatClient.zip)

**Comment by antonypro** [comment]
Please note that this feature is now present!
