### ISSUE TITLE
How to record the Streamed audio?

### ISSUE THREAD

**Issue by paulraj85** [antonypro/AudioStreaming#4]
Hi,
Nice Project Great Work!
Pls help me on how to record and save the streamed audio

**Comment by antonypro** [comment]
Firstly you need to `setGetAudioEnabled(true)`and the other streaming settings of StreamingInfo, then pass it to start function, wait for `adjustSettings` SIGNAL, starts the recorder with a format provided by `audioFormat` and get the played audio with  `veryOutputData(QByteArray)` SIGNAL.

I will attach a simple example for you!
Just set the AudioStreamingLib.pri location properly!

[BroadcastClient.zip](https://github.com/antonypro/AudioStreaming/files/973481/BroadcastClient.zip)

**Comment by paulraj85** [comment]
Thank you! Works Great!
