### ISSUE TITLE
[BroadcastClient] Audio received only for a few milliseconds

### ISSUE THREAD

**Issue by davidebeatrici** [antonypro/AudioStreaming#5]
Hello,

I found this awesome project and decided to compile and test it with the provided demo(s).
Unfortunately the client doesn't work as expected, as the audio stops being received at all after a few milliseconds.
Reconnecting to the server results in the audio working again, temporarily.

Both the client and the server are running on the same Debian machine.

**Comment by antonypro** [comment]
Hi!

I just installed Debian 64 bits in a virtual machine, then i installed Qt Creator with Qt 5.10, built the library and its demos and it just works!

Please provide more info, like if your operating system is 32 or 64 bits, the version of Qt used to build the library and it's examples, and if you got any error/warning text from the demos or from other source.

**Comment by davidebeatrici** [comment]
Hi!

Thank you very much for your answer.

OS: Debian Buster (testing), 64 bit
Qt version: 5.9.2
GCC version: 7.2.0

I get two different warnings while compiling the library:
```cpp
AudioStreaming/AudioStreamingLibCore/AudioStreamingLibCore/3rdparty/eigen3/Eigen/src/Core/AssignEvaluator.h:86: warning: enum constant in boolean context [-Wint-in-bool-context]
     MayLinearVectorize = bool(MightVectorize) && MayLinearize && DstHasDirectAccess
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
```

```cpp
AudioStreaming/AudioStreamingLibCore/AudioStreamingLibCore/3rdparty/eigen3/Eigen/src/Core/AssignEvaluator.h:90: warning: enum constant in boolean context [-Wint-in-bool-context]
     MaySliceVectorize  = bool(MightVectorize) && bool(DstHasDirectAccess)
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~
```

I wanted to test the client again, but now the server crashes as soon as it's started:

```cpp
ASSERT failure in QVector<T>::operator[]: "index out of range", file /usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h, line 430
```

At [waveformwidget.cpp, line 91](https://github.com/antonypro/AudioStreaming/blob/master/Demos/BroadcastServer/waveformwidget.cpp#L91)

Sometimes the client crashed in the same exact way when disconnecting and instantly reconnecting to the server.

More info about the crash:
```
wave_form_vector contains 4410 items
numSamples: 4410
i: 4400
j: 10
```

**Comment by antonypro** [comment]
Hi! Thank you for your feedback and for being so specific!

I couldn't reproduce the warnings of Eigen code, but what you reported does not seem an error or misconfiguration of my code, i believe it's just a warning we can ignore!

About the crash you reported, i see that you found a bug in the `waveformwidget.cpp`, used in Broadcast Server and Broadcast Client demos! The error is about unalignment of the vector size with the number of iterations, if the number of items in the vector is not a multiple of the density, the failure ocurrs, and ocurrs in any OS not only on Debian!

I will correct this problem in the next commit!

Again, thank you, @davidebeatrici!

Antonio Dias!

**Comment by davidebeatrici** [comment]
Hi! Thank you very much for the fix!

Now the demos don't crash anymore, but the audio interruption problem remains, with any buffer times.
I also tried changing the output from Surround 5.1 to Stereo in KDE's audio settings.

Info is the same on both the client and the server:
```
Input format:

Sample size: 32 bits
Sample rate: 44100 hz
Channels: 2
Sample type: Float
Byte order: Little endian

Resampled format:

Sample size: 32 bits
Sample rate: 44100 hz
Channels: 2
Sample type: Float
Byte order: Little endian
```

I noticed that if the buffer time value is less than 10 ms, it results in "0 ms" in the client info.

**Comment by antonypro** [comment]
Hi, @davidebeatrici.

The application won't crash, but the sound is permanently muted until reconnect?

**Comment by davidebeatrici** [comment]
Hi, @antonypro.

That's exactly what I'm experiencing.

**Comment by antonypro** [comment]
@davidebeatrici: The connection also drops? (The interface is equal when initially disconnected).

**Comment by davidebeatrici** [comment]
@antonypro No, the client remains connected.

**Comment by antonypro** [comment]
@davidebeatrici: Sorry for asking too much, but i can't reproduce your problem!

Are the bar indication peak level and RMS level (the black vertical bar on right side), don't indicate any sound on Server nor on Client?

**Comment by davidebeatrici** [comment]
@antonypro: Don't worry at all, feel free to ask me anything!

The client acts as if no sound is being received, as the bars don't show any activity anymore.

The server always works fine, with the bars indicating the correct sound level.

**Comment by antonypro** [comment]
@davidebeatrici: Since i cannot reproduce the error, i will edit the library to show debug messages, so you and others users can report an error with more information and less guessing, but it will take a time! Please wait!

**Comment by davidebeatrici** [comment]
@antonypro: No problem, thank you very much for your help!

**Comment by antonypro** [comment]
@davidebeatrici: I planning to commit the attached file to master, however it’s not sufficiently mature to this.

The attached contains a modified version of `AudioStreamingLib` which reports critical actions performed by the library, so you can see, for example, if data has being written from server to client but none comes to client, also you can see the progress of buffering.

This modified version does not works well with WalkieTalkie only with the Broadcast’s demos.

Please report few messages you got before audio stop, so I can investigate further!

[AudioStreamingLibProjectTest.zip](https://github.com/antonypro/AudioStreaming/files/1610326/AudioStreamingLibProjectTest.zip)

**Comment by davidebeatrici** [comment]
@antonypro: Thank you very much for this!

Where can I see the library messages?

**Comment by antonypro** [comment]
@davidebeatrici: If you're using Qt Creator you can see it in the Application Output tab!
Like any other messages that you write with `qDebug()`.

**Comment by davidebeatrici** [comment]
@antonypro: I didn't see any output because of [this](https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1731646) bug.

Audio stops being reproduced after the last message by the `play()` function.
```cpp
File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 2241
Message: Got Audio Data - Size: 15832 bytes. 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "143" Function: "writePrivate" Record number: 2242
Message: Buffering: 44\300 ms - 14% 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 2243
Message: Got Audio Data - Size: 16888 bytes. 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 2244
Message: Got Audio Data - Size: 0 bytes. 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "143" Function: "writePrivate" Record number: 2245
Message: Buffering: 92\300 ms - 30% 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "143" Function: "writePrivate" Record number: 2246
Message: Buffering: 92\300 ms - 30% 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 2247
Message: Got Audio Data - Size: 17496 bytes. 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 2248
Message: Got Audio Data - Size: 0 bytes. 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "143" Function: "writePrivate" Record number: 2249
Message: Buffering: 142\300 ms - 47% 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "143" Function: "writePrivate" Record number: 2250
Message: Buffering: 142\300 ms - 47% 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 2251
Message: Got Audio Data - Size: 17408 bytes. 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 2252
Message: Got Audio Data - Size: 0 bytes. 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "143" Function: "writePrivate" Record number: 2253
Message: Buffering: 191\300 ms - 63% 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "143" Function: "writePrivate" Record number: 2254
Message: Buffering: 191\300 ms - 63% 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 2255
Message: Got Audio Data - Size: 22584 bytes. 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 2256
Message: Got Audio Data - Size: 0 bytes. 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "143" Function: "writePrivate" Record number: 2257
Message: Buffering: 255\300 ms - 85% 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "143" Function: "writePrivate" Record number: 2258
Message: Buffering: 255\300 ms - 85% 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 2259
Message: Got Audio Data - Size: 17528 bytes. 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 2260
Message: Got Audio Data - Size: 0 bytes. 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "143" Function: "writePrivate" Record number: 2261
Message: Buffering: 305\300 ms - 101% 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "143" Function: "writePrivate" Record number: 2262
Message: Buffering: 305\300 ms - 101% 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "197" Function: "play" Record number: 2263
Message: Playing... 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "237" Function: "play" Record number: 2264
Message: Writing 20 ms to output device. 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "237" Function: "play" Record number: 2265
Message: Writing 20 ms to output device. 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 2266
Message: Got Audio Data - Size: 17384 bytes. 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 2267
Message: Got Audio Data - Size: 0 bytes. 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 2268
Message: Got Audio Data - Size: 17416 bytes. 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 2269
Message: Got Audio Data - Size: 0 bytes. 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 2270
Message: Got Audio Data - Size: 17368 bytes. 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 2271
Message: Got Audio Data - Size: 0 bytes. 
```

**Comment by antonypro** [comment]
@davidebeatrici: Please add the following debug message to `audiooutput.cpp`, line 207:
    
    LIB_DEBUG(VERBOSE_LEVEL_2, "Chunks:" << chunks);

Then compile the lib and the Broadcast's demos, post the log and i'll be able to see if the program is  entering in the loop `while (chunks)`.

**Comment by davidebeatrici** [comment]
@antonypro: Here's the log:

```cpp
File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 370
Message: Got Audio Data - Size: 15808 bytes. 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "143" Function: "writePrivate" Record number: 371
Message: Buffering: 44\300 ms - 14% 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 372
Message: Got Audio Data - Size: 15808 bytes. 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "143" Function: "writePrivate" Record number: 373
Message: Buffering: 89\300 ms - 29% 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 374
Message: Got Audio Data - Size: 17176 bytes. 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 375
Message: Got Audio Data - Size: 0 bytes. 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "143" Function: "writePrivate" Record number: 376
Message: Buffering: 138\300 ms - 46% 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "143" Function: "writePrivate" Record number: 377
Message: Buffering: 138\300 ms - 46% 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 378
Message: Got Audio Data - Size: 22752 bytes. 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 379
Message: Got Audio Data - Size: 0 bytes. 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "143" Function: "writePrivate" Record number: 380
Message: Buffering: 202\300 ms - 67% 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "143" Function: "writePrivate" Record number: 381
Message: Buffering: 202\300 ms - 67% 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 382
Message: Got Audio Data - Size: 17344 bytes. 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 383
Message: Got Audio Data - Size: 0 bytes. 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "143" Function: "writePrivate" Record number: 384
Message: Buffering: 251\300 ms - 83% 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "143" Function: "writePrivate" Record number: 385
Message: Buffering: 251\300 ms - 83% 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 386
Message: Got Audio Data - Size: 16856 bytes. 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 387
Message: Got Audio Data - Size: 0 bytes. 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "143" Function: "writePrivate" Record number: 388
Message: Buffering: 299\300 ms - 99% 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "143" Function: "writePrivate" Record number: 389
Message: Buffering: 299\300 ms - 99% 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 390
Message: Got Audio Data - Size: 17088 bytes. 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 391
Message: Got Audio Data - Size: 0 bytes. 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "143" Function: "writePrivate" Record number: 392
Message: Buffering: 348\300 ms - 116% 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "143" Function: "writePrivate" Record number: 393
Message: Buffering: 348\300 ms - 116% 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "197" Function: "play" Record number: 394
Message: Playing... 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "208" Function: "play" Record number: 395
Message: Chunks: 2 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "239" Function: "play" Record number: 396
Message: Writing 20 ms to output device. 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "239" Function: "play" Record number: 397
Message: Writing 20 ms to output device. 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "208" Function: "play" Record number: 398
Message: Chunks: 0 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "208" Function: "play" Record number: 399
Message: Chunks: 0 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "208" Function: "play" Record number: 400
Message: Chunks: 0 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "208" Function: "play" Record number: 401
Message: Chunks: 0 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "208" Function: "play" Record number: 402
Message: Chunks: 0 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 403
Message: Got Audio Data - Size: 16920 bytes. 

File: "../AudioStreamingLibCore/worker.cpp" Line: "1001" Function: "processClientInput" Record number: 404
Message: Got Audio Data - Size: 0 bytes. 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "208" Function: "play" Record number: 405
Message: Chunks: 0 

File: "../AudioStreamingLibCore/audiooutput.cpp" Line: "208" Function: "play" Record number: 406
Message: Chunks: 0 
```

**Comment by antonypro** [comment]
@davidebeatrici: It may be a problem with your OS, your hardware or most probably a problem with Qt in your environment.

Just to make sure it's isn't a problem specific of my library, please tell me if you can hear anything in the attached example.

It's an example which comes with Qt. I'm posting here for convenience.

[audiooutput.zip](https://github.com/antonypro/AudioStreaming/files/1612832/audiooutput.zip)

**Comment by davidebeatrici** [comment]
@antonypro: The example works perfectly.

**Comment by antonypro** [comment]
@davidebeatrici: Since you said the Qt example is working, i wonder if the problem exists due to an incompatibility of your environment and floating point samples, so i have modified the library to use signed integer/16 bits samples internally.

If you still having problems, please post the log, if the problem is solved, please let me know.

And again, thank you for your valuable feedback!

[AudioStreamingLibProjectTest.zip](https://github.com/antonypro/AudioStreaming/files/1617192/AudioStreamingLibProjectTest.zip)

**Comment by davidebeatrici** [comment]
@antonypro: It works!

Thank you very much for your help!

**Comment by davidebeatrici** [comment]
@antonypro: After some testing, I noticed that every kind of audio is reproduced correctly, except high pitched sounds, which are distorted.

Could it be related to the change you did in order to get the library to work for me?

**Comment by antonypro** [comment]
@davidebeatrici: About the solved error, it's weird that Qt does not detect the floating point samples as unsupported format, because it works on Android!

About the distorted sounds it's not related to the solution, but is related to the way we apply volume to samples. Instead of a linear scale of 0.0 to 1.0 now I'm using a logarithmic scale and applying a -6,0 db attenuation in the amplitude of each sample!

I hope in a short time commit the changes to the master branch, for now please use the attached file.

If you find any problem or have a suggestion feel free to tell me!

[AudioStreamingLibProjectTest.zip](https://github.com/antonypro/AudioStreaming/files/1618787/AudioStreamingLibProjectTest.zip)

**Comment by davidebeatrici** [comment]
@antonypro: The attached project works perfectly!

I didn't find any problems, aside from the buffer time being 0 ms if set to a value below 10 ms, but I think it's better if I create another issue for that.

Thank you very much for your help!

**Comment by davidebeatrici** [comment]
@antonypro Thank you very much for the fix!
