### ISSUE TITLE
Is the opus decode feature not available on RPI3?

### ISSUE THREAD

**Issue by MS-C0d3r** [antonypro/AudioStreaming#9]
Hi, I am using this library in Windows10 and RPI3.

Windows10 is a server and RPI3 is a client.

Windows10 succeeded in compressing audio into an operating codec.

However, unknown device (RPI3) does not support Opus codec.

![capture](https://user-images.githubusercontent.com/46777374/52109806-0b40bd80-2642-11e9-8837-35b70486828a.JPG)

Is there any way to use the Opus Decode function on RPI3?

**Comment by antonypro** [comment]
The possibility to configure Opus and OpenSsl settings for unknown device was now added!

**Comment by MS-C0d3r** [comment]
Thank you! It now works well with RPI3
